server:
    address: :2002
    model: debug

#数据库配置
db:
  dialects: mysql
  host: 127.0.0.1
  port: 3306
  db: go-admin-api
  username: root
  password: 119347
  charset: utf8
  #最大空闲数
  maxIdle: 50
  #最大连接数
  maxOpen: 100

#redis配置
redis:
  address: 127.0.0.1:6379
  password:

#picture配置
imageSettings:
  uploadDir: /admin-go-api/upload/
  imageHost: http://localhost:2002


#log配置
log:
  path: /admin-go-api/log/
  name: admin-go-api.log
  model: console
